#!/bin/sh
cd "${0%/*}" || exit 1   # run from this directory

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

# polyMesh をシンボリックリンクで参照
if [ ! -e constant/polyMesh ]; then
    ln -s ../../LK-1_HD0.45/constant/polyMesh constant/polyMesh
fi

restore0Dir

runApplication decomposePar

runParallel simpleFoam

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
